### ISSUE TITLE
Reason for large git-annex repository when cloning

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#202]
Hello! When cloning a git-annex repos, I notice it is about 600MB large:
~~~
julien-macbook:~/data.neuro $ git clone git@data.neuro.polymtl.ca:datasets/sci-zurich
Cloning into 'sci-zurich'...
remote: Énumération des objets: 7761, fait.
remote: Décompte des objets: 100% (7761/7761), fait.
remote: Compression des objets: 100% (3539/3539), fait.
remote: Total 7761 (delta 3507), réutilisés 4229 (delta 1930), réutilisés du pack 0
Receiving objects: 100% (7761/7761), 630.19 MiB | 7.49 MiB/s, done.
Resolving deltas: 100% (3507/3507), done.
Updating files: 100% (824/824), done.
~~~

It's not a problem per se, but I'm just curious given that I thought the point of git-annex is to only get the "big" data after running `git-annex get .`?

**Comment by mguaypaq** [comment]
You're right, it looks like the sci-zurich dataset got some non-annexed images. Looking at the git-annex configuration, I see:
```
sci-zurich$ cat .gitattributes 
*   annex.largefiles=anything
*.nii.gz   filter=annex
*.nii   filter=annex
*.tif   filter=annex
```

which is different from the suggested configuration [in our wiki](https://intranet.neuro.polymtl.ca/geek-tips/git-annex.html#new-repo):
```
# Normalize line-endings to \n
*             text=auto

# Configure filetypes stored by git-annex.
# by default git-annex sets * filter=annex, but that is very slow:
# it copies even non-annexed files through git-annex even though it will decide not to handle them.
# this overrides that behaviour so that only annexed files must be processed.
*             annex.largefiles=nothing
*.nii.gz      filter=annex annex.largefiles=anything
*.nii         filter=annex annex.largefiles=anything
*.tif         filter=annex annex.largefiles=anything
```

Maybe because of this, the latest commit on the master branch (`5cdccf6f6197a50443775f91047d1692513c5254`) contains a bunch of non-annexed large files. I can fix the configuration and do some git surgery to remove the large files.

Apart from lots of `.nii.gz` files, there are also a few large `.roi` files. They look like text files, but a few of them are several tens (or hundreds) of kilobytes. Should I make `.roi` files also be annexed while I'm at it?

**Comment by jcohenadad** [comment]
> Apart from lots of .nii.gz files, there are also a few large .roi files. They look like text files, but a few of them are several tens (or hundreds) of kilobytes. Should I make .roi files also be annexed while I'm at it?

if it's easy for you to do, yes, if not, don't worry about it

**Comment by mguaypaq** [comment]
Ok, I've done the git surgery so that all `.nii.gz` files are git-annexed. I decided not to git-annex the `.roi` files because there's only a few large-ish ones, and it would probably cause more trouble than it's worth.

@jcohenadad, @naga-karthik, @kiristern, if you have local copies of the `datasets/sci-zurich` repository, you may want to create some fresh clones with `git clone git@data.neuro.polymtl.ca:datasets/sci-zurich`, to avoid re-creating the large files in the repository in the future. If you have some local changes that aren't yet on the server, I can help you make sure they don't get lost.

I've got a copy of the (pre-surgery) original repository on `joplin` that I'll keep for a few weeks just in case we discover problems. But a quick test shows that all the files seem to be there, with a much smaller download for `git clone` (around 21MB, instead of 600MB):
```
u119414@joplin:~/data_nvme_u119414$ git clone git@data.neuro.polymtl.ca:datasets/sci-zurich
Cloning into 'sci-zurich'...
remote: Énumération des objets: 7763, fait.
remote: Décompte des objets: 100% (7763/7763), fait.
remote: Compression des objets: 100% (3585/3585), fait.
remote: Total 7763 (delta 3458), réutilisés 4265 (delta 1887), réutilisés du pack 0
Receiving objects: 100% (7763/7763), 2.02 MiB | 18.93 MiB/s, done.
Resolving deltas: 100% (3458/3458), done.
u119414@joplin:~/data_nvme_u119414$ cd sci-zurich
u119414@joplin:~/data_nvme_u119414/sci-zurich$ du -sh
21M	.
u119414@joplin:~/data_nvme_u119414/sci-zurich$ git annex get
(merging origin/git-annex into git-annex...)
(recording state in git...)
(scanning for unlocked files...)
get derivatives/labels/sub-zh01/ses-01/anat/sub-zh01_ses-01_acq-sag_T2w_lesion-manual.nii.gz (from origin...) 
ok                                
get derivatives/labels/sub-zh01/ses-02/anat/sub-zh01_ses-02_acq-sag_T2w_lesion-manual.nii.gz (from origin...) 
ok                                

<...snip...>

get sub-zh81/ses-01/anat/sub-zh81_ses-01_acq-sag_T1w.nii.gz (from origin...) 
ok                                
get sub-zh81/ses-01/anat/sub-zh81_ses-01_acq-sag_T2w.nii.gz (from origin...) 
ok                                
(recording state in git...)
u119414@joplin:~/data_nvme_u119414/sci-zurich$ du -sh
1.2G	.
```

**Comment by jcohenadad** [comment]
> if you have local copies of the datasets/sci-zurich repository, you may want to create some fresh clones with git clone git@data.neuro.polymtl.ca:datasets/sci-zurich, to avoid re-creating the large files in the repository in the future.

done!

**Comment by naga-karthik** [comment]
I also cloned the latest version following this update. My latest changes were merged to main just before this so I have no more local changes on my end!

**Comment by kiristern** [comment]
for me as well. i cloned the latest version

**Comment by naga-karthik** [comment]
@mguaypaq I see the `.roi` files for the derivatives though. Is this intended? That is, were only the `.roi` files for the images were in the latest git-annexed version? (Note that these `.roi` files are very small, but just wanted to clarify)

**Comment by mguaypaq** [comment]
I didn't end up changing anything about the `.roi` files: since they're not too large, I kept all of them in the repository (and not git-annexed, so you get them directly with a `git clone`, no need for `git annex get`).

If your question is whether these files should be part of the dataset at all, I have no idea sorry!

**Comment by naga-karthik** [comment]
@mguaypaq nvm my comment, I misunderstood the point of git-annex. Thank you for the clarification, though. This is now resolved, so closing it.

**Comment by mguaypaq** [comment]
> I've got a copy of the (pre-surgery) original repository on `joplin` that I'll keep for a few weeks just in case we discover problems.

It's been a few weeks with no problems, so I've gotten rid of this temporary backup copy.
