### ISSUE TITLE
`dcm-zurich` - add disc labels for T2w sagittal images

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#226]
In the `jv/add_t2w_sag_labeling` branch, I added disc labels for T2w sagittal images for 134 subjects:

- manually corrected disc labels for 69 subjects (commit `57dac5d6e758c0436a20aaf81fbc51e4b23d912e`)
- automatically generated (by `sct_label_vertebrae`) and visually inspected disc labels for 65 subjects (`0305a44f46a512067ceb315fd20e19a2eb684650`)

Thanks @NathanMolinier for the manual correction of disc labels! 💯

**Comment by mguaypaq** [comment]
I saw that you added a bunch of empty JSON files, is there a reason for that?

While thinking about this question, I ran bids-validator and thought would complain about them, because empty JSON files are usually not allowed, but there was no error or warning. Then I saw that the empty JSON files are under `derivatives/labels/`, which `bids-validator .` doesn't check at all (because it's considered a separate dataset).

So then I tried running `bids-validator derivatives/labels/`, because maybe we want the derivative to also be BIDS-compliant? Then it finally complained about the empty JSON files, but also a bunch of other errors and warnings that aren't part of this issue (but maybe we should discuss at some point).

**Comment by mguaypaq** [comment]
I can still merge this PR into master regardless of `bids-validator derivatives/labels/`, as long as you have a reason for the empty JSON files.

**Comment by mguaypaq** [comment]
After some in-person discussion: we probably want to record in the JSON sidecars that @NathanMolinier checked these automatically generated labels, so it's not quite "Author", but we're not sure what to call the field. I'll merge this branch into master for now, and we can fix the JSON sidecars later.
