### ISSUE TITLE
`dcm-zurich` - add clinical data

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#256]
In the `jv/add_clinical_data` branch, I added 5 XLSX tables with clinical data to the `dcm-zurich/phenotype` folder. I also included a brief `README.md` describing individual files.

```
phenotype
├── README.md
├── anatomical_data.xlsx
├── clinical_scores.xlsx
├── electrophysiological_measurements.xlsx
├── motion_data.xlsx
└── motion_data_maximum_stenosis.xlsx
```

Related to https://github.com/neuropoly/data-management/issues/239

**Comment by valosekj** [comment]
@sandrinebedard and I decided to keep the XLSX files because our script for computing statistics is already compatible with the XLSX files.

@mguaypaq could you please merge the branch?

**Comment by mguaypaq** [comment]
This looks fine. I notice that the XLSX files are directly in git, rather than git-annex, but they are in total less than 250kB. However, if they have to be modified often, then they will quickly inflate the size of the repository, and slow down `git clone`. So, I'll merge this as-is, and if we have to modify the XLSX files again later, I'll configure git-annex to handle them at that point.

bids-validator complains about the README.md and the XLSX files, so I added them to a `.bidsignore` file as an extra commit.

Rebased and merged into master.
