### ISSUE TITLE
`sci-colorado` - add clinical data 

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#258]
In the `jv/add_clinical_data` branch, I added clinical data to the `participants.tsv` file. I also added corresponding fields to the `participants.json` file.

@mguaypaq could you please merge the branch?

**Comment by mguaypaq** [comment]
I ran bids-validator, which spotted some mistakes. I fixed most of them in an extra commit:

* Removed trailing commas in `participants.json`, which are invalid in JSON
* Fixed typo (double space) in `LongName` of `discharge_LEMS`
* Removed trailing space after `discharge_pin_prick_right` in header line of `participants.tsv`
* Removed empty file `sub-6013/anat/sub-6013_T2w.json`

There are the usual errors of INCONSISTENT_PARAMETERS and NO_AUTHORS, but also:

* 3 subjects are missing a T1w image: `sub-5445`, `sub-5656`, `sub-5844`. There's no mention of this in the README.
* The JSON sidecar for `sub-6013/anat/sub-6013_T2w` (which I removed because it was empty) should probably not have been empty, because the corresponding image file is present. The other JSON sidecars for T2w images have lots of metadata, but not this one.

These problems are unrelated to this PR, so I merged into master and deleted the branch `jv/add_clinical_data` anyway.

**Comment by mguaypaq** [comment]
Ah, also I just noticed that there are some image files from a previous commit that are in plain git, rather than being git-annexed. I'll fix the problem and rebase master.

**Comment by valosekj** [comment]
> I ran bids-validator, which spotted some mistakes. I fixed most of them in an extra commit:

Sorry about that. I ran the `bids-validator` by myself, and it did not raise any of the errors related to `participants.json` or `participants.tsv`:

<img width="1620" alt="image" src="https://github.com/neuropoly/data-management/assets/39456460/09489648-482d-4631-8ae8-2ec739e0dbed">

> 3 subjects are missing a T1w image: sub-5445, sub-5656, sub-5844. There's no mention of this in the README.

Good catch! Could you please add this info to the README?

> The JSON sidecar for sub-6013/anat/sub-6013_T2w (which I removed because it was empty) should probably not have been empty, because the corresponding image file is present. The other JSON sidecars for T2w images have lots of metadata, but not this one.

Yeah, I also noticed this. I do not know the reason why the JSON sidecar was empty for this particular image.

**Comment by mguaypaq** [comment]
> Sorry about that. I ran the `bids-validator` by myself, and it did not raise any of the errors related to `participants.json` or `participants.tsv`:

Yeah, bids-validator has the unfortunate behavior that sometimes it stops looking for more errors after finding some. In this case, all the other errors were only detected after I deleted the empty JSON file.

**Comment by mguaypaq** [comment]
Ok, I rebased the branches `master` and `af/fix_data` after making sure that all images are git-annexed. For safety, please delete and re-clone any local copies of the `sci-colorado` repo before making any more changes.

**Comment by mguaypaq** [comment]
Also, I'll note that the branch `af/fix_data` would be worth investigating?

**Comment by valosekj** [comment]
> Also, I'll note that the branch `af/fix_data` would be worth investigating?

Okay! We can check the branch together!

**Comment by mguaypaq** [comment]
Regarding the `af/fix_data` branch:
- It was created for #174, back in March 2022.
- The issue lists a very large diff, but in fact the `af/fix_data` branch only touches 16 files (8 images, and the 8 corresponding json sidecars).
- Since you were mentioned in the issue, @naga-karthik, do you remember any context?
- @valosekj checked all the changed images visually and:
  - The 6 T2w images are visually identical (for subjects 5828, 5844, 6002, 6004, 6013, 6026), have the same transformation matrices, and have only slightly different header fields.
  - The 2 T1w images are visually completely different (for subjects 6002, 6004).
- For the json sidecars, they are basically completely different: some don't even have the same MagneticFieldStrength (1.5 versus 3)

Presumably the more recent data is correct, but it's such a big difference that it would be nice to know more about what's going on.

**Comment by naga-karthik** [comment]
Unfortunately, I don't reacall anything about the `af/fix_data` branch for this dataset :( 

@valosekj just to confirm, this branch is not adding new subjects right? It's the json sidecar info?

**Comment by valosekj** [comment]
> @valosekj just to confirm, this branch is not adding new subjects right? It's the json sidecar info?

Correct. The branch does not add new subjects. It only updates JSON sidecars of T2w images for six subjects (see https://github.com/neuropoly/data-management/issues/258#issuecomment-1701233567). Also, the branch updates/changes T1w images for two subjects -- this should be fine for our SCIseg project since we use only T2w scans.

**Comment by valosekj** [comment]
> Presumably the more recent data is correct,

I guess so. 

>  but it's such a big difference that it would be nice to know more about what's going on.

Unfortunately, we cannot answer this ourselves- we would have to reach out to the collaborators.

**Comment by valosekj** [comment]
As discussed in the SCT developer meeting of 2023-09-07 ([minutes](https://docs.google.com/document/d/1ItApJQfajO2lRzOU2yenWbeRg6alfsdut3J4AVVdo78/edit#heading=h.cko7kqkgid08)), I will contact collaborators to verify which version of images is the right one.

**Comment by valosekj** [comment]
Hey! A few updates!
Andrew Smith shared with me DICOM files for the problematic subjects ([comment #258](https://github.com/neuropoly/data-management/issues/258#issuecomment-1701233567), [issue #59](https://github.com/ivadomed/model_seg_sci/issues/59)). I converted the DICOM files to NIfTI using `dcm2niix` and checked the images and their JSON sidecars. Below are my updates.

I pushed the updated files to the `jv/fix_data` branch. @mguaypaq, could you please check the branch and merge it if you find everything ok?

## T2-w images

Context: [comment #258](https://github.com/neuropoly/data-management/issues/258#issuecomment-1701233567)

I updated T2w JSON sidecars for subjects sub-5844, sub-6002, sub-6004, sub-6013, sub-6026.
The updated JSON sidecars now have 3T field strength instead of 1.5T. Since information about the field strength is also contained in the nii header, I also updated the nii images. I visually checked the images; they are the same, i.e., only the header has been updated.

For sub-5828, the provided T2w image has the same 3T field strength BUT a different 6mm slice thickness relative to the 3.3mm slice thickness of the images under the git-annex (both `af/fix_data` and `master`). Due to the difference in the slice thickness, the 6mm slice thickness image covers different FOV and is not compatible with lesion and SC labels under derivatives. Thus, I would continue with the 3.3mm slice thickness image under the git-annex.

## T1-w images

Context: [comment #258](https://github.com/neuropoly/data-management/issues/258#issuecomment-1701233567)

I updated T1w images and JSON sidecars for sub-6002 and sub-6004. The new images are visually different. But it should be fine because we have yet to use T1w images.

## sub-5740_T2w.nii.gz - weird intensity range

Context: [issue #59](https://github.com/ivadomed/model_seg_sci/issues/59)

Even the newly provided image has the same weird intensity range --> we can keep the original.

**Comment by mguaypaq** [comment]
Thanks for the updates. I added two commits:
1. To mention the three subjects with missing T1w images in README.md (renamed and reformatted from README).
2. To configure bids-validator to ignore INCONSISTENT_PARAMETERS, INCONSISTENT_SUBJECTS, NO_AUTHORS.

Git-annex and bids-validator are both happy, so I merged into master. I also deleted both branches `af/fix_data` and `jv/fix_data`.
