### ISSUE TITLE
New data in `data_axondeepseg_wakehealth_training`

### ISSUE THREAD

**Issue by hermancollin** [neuropoly/data-management#287]
Hi. I added a new image and an annotation I made to `data_axondeepseg_wakehealth_training`. The branch is `ac/add_test_image`.

It passes the bids-validator on my side.

**Comment by mguaypaq** [comment]
The git repository was bigger than I expected when downloading, and I see that there were some images files outside of git-annex (all the `.png` files, and some of the `.tif` files in the git history).

For the `.png` files, I need to change the configuration in `.gitattributes` to fix it, and then re-commit the files.

For the old `.tif` files, I'll need to do a `git rebase` to fix the history, so you may have to delete and re-clone the repository afterwards.

**Comment by hermancollin** [comment]
@mguaypaq thank you for looking into this. I am not surprised that the PNGs are not git annexed, because I changed the gitatteibutes in this branch but they were already uploaded... I wasn't sure how to annex them. As for the TIFs, this is a bit more surprising.
What do you use to see where the files are located? Is it `git annex whereis`?

**Comment by mguaypaq** [comment]
I think the most recent TIFs are correctly git-annexed. But the git history still contains the old versions, which were not annexed. If you want to see, you can run `git log --stat` and look for lines which contain the string `Bin`, indicating a binary file (and the file size in bytes).

The fact that git can still recover old versions of files is usually a great feature! It's only a problem for large files that are accidentally added to git, and then deleted. In that case, we have to dig deeper and remove the files from the history as well.

**Comment by mguaypaq** [comment]
Ok, I've been able to clean the large files from the git history of the `master` branch on my local clone of the repository. But now I have some questions before I can integrate the new commits from your branch.

It looks like the `master` branch contains two commits to change the naming scheme of some files, which are not present on this branch `ac/add_test_image`. I think the naming schemes are not the same between the two branches. Do you want to keep the "rollback" commits from the master branch or not?

Also, what's the deal with the branch `ac/consistent_with_bf_dataset`?

Here's the git log graph:
```
* commit 8c48cfe4579c98a423fdd2f99a5eeef3a19af1ca (origin/ac/add_test_image)
| Author: Armand Collin <armac@videotron.ca>
| Date:   Thu Dec 14 13:17:37 2023 -0500
| 
|     Add sourcedata for test subject
| 
* commit 559fa2626204645d692c60a75a8f213dc7d7e0ec
| Author: Armand Collin <armac@videotron.ca>
| Date:   Thu Dec 14 13:17:22 2023 -0500
| 
|     Add new test subject + annotation
| 
* commit cc03eb1fdb99bb92b17988d76d1d0af258e922e8
| Author: Armand Collin <armac@videotron.ca>
| Date:   Thu Dec 14 13:16:48 2023 -0500
| 
|     Update metadata and add authors field
| 
* commit 52e5113fbf06de2469b90c3814475e486bb5d65b (origin/ac/consistent_with_bf_dataset)
| Author: Armand Collin <armac@videotron.ca>
| Date:   Thu Feb 10 14:42:23 2022 -0500
| 
|     Updated README
|   
| * commit c72b3722eb0a327a3b7f666ecbacad529fa95fff (origin/master, origin/HEAD, master)
| | Author: Armand Collin <armac@videotron.ca>
| | Date:   Fri Feb 11 11:10:38 2022 -0500
| | 
| |     Rolled back labels
| | 
| * commit b202f59498ac0376063b341c2b7772cf5792e953
|/  Author: Armand Collin <armac@videotron.ca>
|   Date:   Fri Feb 11 10:24:09 2022 -0500
|   
|       Rolled back the original filenames used for training
| 
* commit 2a4093da593ccbb5ca92138df466a1afb048b97f
  Author: Armand Collin <armac@videotron.ca>
  Date:   Thu Feb 10 14:24:34 2022 -0500
  
      Added back all data
```

**Comment by hermancollin** [comment]
@mguaypaq hmm I don't remember why this was not merged. I think we weren't sure with Marie-Hélène of the exact naming scheme, so we put it on hold. I think we can safely ignore this branch. Also I don't mind the rollbacks.

**Comment by mguaypaq** [comment]
Ok, it was a bit difficult, but the final solution was:
- I rewrote the original 4 commits to remove the large files from the plain git history. So the commits:

  1. `Initial commit` (f2949e3aa3954471ade619b0817cfd5f3f087f63)
  2. `Configure git-annex` (0cadf1f7edf42dfaaa88b3ec6a1950907b455229)
  3. `Removed all the data` (83d0d06c387fd465db51e24be9977fa72d14ea23)
  4. `Added back all data` (2a4093da593ccbb5ca92138df466a1afb048b97f)

  became just:

  1. `Configure git-annex` (c220bc398df2c1808e2bc037c32bea6965c75815)
  2. `Initial commit` (9aa39d3a7fcc7a91ea882152c226a57291768e6a)

- I rebased the branches `ac/consistent_with_bf_dataset` and `ac/add_test_image` on top of this clean history.

- Instead of rebasing these branches on top of the two rollback commits from `master`, it was simpler (and I think safer) to do it the other way around: so I rebased the two rollback commits from `master` on top of `ac/add_test_image`.

This means that:
- The repository has a linear history, with all large files annexed.
- `ac/add_test_image` is merged into `master`
- `ac/consistent_with_bf_dataset` still exists, because it's referenced in the `README` file.
- Bids-validator complains about the filenames, because they're intentionally following the original, non-BIDS naming scheme from the start of the project.

Because of the history rewriting and the force pushes I had to do, you should make a new clone of the repository, instead of working with your existing clones.

@hermancollin can you make a new clone and check that you're happy with the file names and everything?

**Comment by hermancollin** [comment]
Hey @mguaypaq. Thanks a lot for looking into this! I feel bad for giving you so much work but I think you did a great job. I cloned the repo and everything looks good.

To close this discussion, let me add some context. I created this dataset 2 years ago and at that time, the microscopy integration into BIDS was still a WIP. Marie-Hélène, who was the main contributor to this BIDS extension proposal, gave some recommendations for the filenames for this specific case, but the discussion went stale and no one ever tied this loose end. I think this was my first experience with git-annex and my understanding of the `.gitattributes` file was rudimentary. This explains the messy `Removed all the data` and `Added back all data` commits.
Now I know how git-annex/BIDS work, and I try not to get into convoluted filenaming conundrums anymore. Still, it seems I messed up again last month by basing my working branch on this weird `ac/consistent_with_bf_dataset` branch.

Point is: adding 1 image and 1 GT should not be that complicated, and I apologize for this mess.

**Comment by mguaypaq** [comment]
Thanks for the context! And don't worry, git-annex is pretty complicated, so everyone makes mistakes.

Since everything looks good, I'll close this issue. Feel free to open a new issue if you ever want to change the filenames or add more data again.
