### ISSUE TITLE
Add sacrum segmentation to `spider-challenge-2023` and `whole-spine`

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#302]
## Description

I just created and pushed sacrum segmentations on two different datasets, namely `spider-challenge-2023` and `whole-spine`.

I called the new branch `nm/add_sacrum_seg`, in both cases.

For the `spider-challenge-2023`, the sacrum masks were generated for every subjects because the FOV is lumbar. However, for the `whole-spine` dataset, sacrum segmentations were generated for only 6 subjects because in most cases the sacrum was not present in the field of view.

## Question

In the future, should I create 2 separate issues for the 2 datasets ?

**Comment by mguaypaq** [comment]
It's probably better to open 2 separate issues, because each one gets merged into master independently. And if they're very related, you can cross-reference them in the issue description.

Anyway in this case:
- [X] git-annex, bids-validator, and json sidecars are fine for `spider-challenge-2023`, merged into master.
- [X] git-annex, bids-validator, and json sidecars are fine for `whole-spine`, merged into master.
