### ISSUE TITLE
Cloning a repository effectively downloads the data under .git/ tree

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#41]
So far when I was using datalad, a `git clone` would not download the data. Only when fetching the data on demand would download them. 

Now, when trying to clone a large dataset, e.g. `datasets/uk-biobank` it is effectively downloading ~20GB of data, even _before_ asking to fetch the data with `git-annex get`. Is that an expected behaviour? Is there something we can do about it @kousu ?

Possibly related to https://github.com/neuropoly/data-management/issues/34 and https://github.com/neuropoly/data-management/issues/23

**Comment by jcohenadad** [comment]
Note: I've tried using `git clone --depth=1`, which is super fast, but then I cannot "git-annex get" the images afterwards.

**Comment by kousu** [comment]
@alexfoias's `af/add_subj` branch added the niftis to git directly instead of the annex:

```
git@data:~/repositories/datasets/uk-biobank.git$ git log --stat af/add_subj
commit 327e730f2d6499abc42a1d40816d268c91490b64 (synced/af/add_subj, af/add_subj)
Author: Alexandru Foias <alexandrufoias@gmail.com>
Date:   Fri Jan 22 11:58:13 2021 -0500

    git-annex in alfoi@joplin:~/uk-biobank

 .gitignore                              |   1 +
 sub-1047366/anat/sub-1047366_T1w.json   |  12 ++++++++++++
 sub-1047366/anat/sub-1047366_T1w.nii.gz | Bin 0 -> 16513453 bytes
 sub-1047366/anat/sub-1047366_T2w.json   |  12 ++++++++++++
 sub-1047366/anat/sub-1047366_T2w.nii.gz | Bin 0 -> 11855939 bytes
 sub-1047371/anat/sub-1047371_T1w.json   |  12 ++++++++++++
 sub-1047371/anat/sub-1047371_T1w.nii.gz | Bin 0 -> 18328434 bytes
 sub-1047371/anat/sub-1047371_T2w.json   |  12 ++++++++++++
 sub-1047371/anat/sub-1047371_T2w.nii.gz | Bin 0 -> 12863457 bytes
```

Perhaps a version incompatibility? Or maybe `git annex init` didn't finish properly? Drat.

This is the same issue as https://github.com/neuropoly/spinalcordtoolbox/issues/3100. But because we've got our own server in this case we can avoid this by installing a pre-receive hook!

**Comment by kousu** [comment]
So to fix this this:

1. Delete and redo `af/add_subj` properly
2. Install a `pre-receive` hook to avoid this accident in the future.
  - we should be able to safely make it reject all .nii.gz files larger than 103 bytes, which is the size of a git-annex pointer. We can set that to, say, 1KB just in case.

**Comment by jcohenadad** [comment]
> This is the same issue as neuropoly/spinalcordtoolbox#3100. But because we've got our own server in this case we can avoid this by installing a pre-receive hook!

that would be awesome

**Comment by kousu** [comment]
1. We redid `af/add_subj` and deleted it.

First, the bug turned out to be mixing git-annex v7 and git-annex v8. We installed git-annex v8 from conda:

```
conda install -c conda-forge git-annex
git annex version # -> verify it's now v8
```

Then we made a branch off the branch to redo it:

```
git checkout -b af/add_subj_2
git reset HEAD~ # *soft* reset
git add .
git commit
```

Then we synced that back:

```
git annex sync --content
```

After checking it over a bit, we deleted the old branch:

```
git push origin --delete af/add_subj
git push origin --delete synced/af/add_subj # git-annex cruft
```
(and @alexfoias [tidied up](https://xkcd.com/1597/):

```
cd ..
chmod -R +w uk-biobank/.git
rm -r uk-biobank
git clone git@data.neuro.polymtl.ca:datasets/uk-biobank.git
```
)

2. https://github.com/neuropoly/data-management/issues/43
