### ISSUE TITLE
git annex sync -- content failed on uk-biobank-processed

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/data-management#52]
## Description
I am trying to add processed images to `datasets/uk-biobank-processed`. I followed these [instructions](https://github.com/neuropoly/data-management/blob/master/internal-server.md#upload). Everything went smoothly until `git annex sync --content`.
This is the error that I got when running `git annex sync --content`:
(this is the end only, I added bellow my comlpete terminal history)

~~~
  transfer failed
failed
copy sub-1141841/anat/sub-1141841_T2w.nii.gz
  Lost connection (fd:14: hGetChar: end of file)
(unable to check origin) failed
push origin
FATAL: W any datasets/uk-biobank-processed sandrine DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: W any datasets/uk-biobank-processed sandrine DENIED by fallthru(or you mis-spelled the reponame)fatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.  Pushing to origin failed.
failed
git-annex: sync: 1301 failed
~~~

Here is my complete terminal history from `git add` to `git annex sync --content`:

[terminal_joplin_git_annex.txt](https://github.com/neuropoly/data-management/files/6193886/terminal_joplin_git_annex.txt)

**Comment by kousu** [comment]
Ceci est une très bon reportage. Je m'occupe ! Tue Mar 23 22:20:52 EDT 2021 neuropoly/data-management ***@***.***>: Description I am trying to add processed images to datasets/uk-biobank-processed. I followed these instructions. Everything went smoothly until git annex sync --content. This is the error that I got when running git annex sync --content: (this is the end only, I added bellow my comlpete terminal history) transfer failed failed copy sub-1141841/anat/sub-1141841_T2w.nii.gz Lost connection (fd:14: hGetChar: end of file) (unable to check origin) failed push origin FATAL: W any datasets/uk-biobank-processed sandrine DENIED by fallthru (or you mis-spelled the reponame) fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. FATAL: W any datasets/uk-biobank-processed sandrine DENIED by fallthru(or you mis-spelled the reponame)fatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists. Pushing to origin failed. failed git-annex: sync: 1301 failed Here is my complete terminal history from git add to git annex sync --content: terminal_joplin_git_annex.txt — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kousu** [comment]
Easy fix: you lacked permission.

I fixed it with:

```
$ ssh git@localhost perms datasets/uk-biobank-processed + WRITERS sandrine
```

Thanks for the reminder. I've added that part to this section in #35:

https://github.com/neuropoly/data-management/blob/c521bc7/internal-server.md#upload
https://github.com/neuropoly/data-management/blob/c521bc7/internal-server.md#permissions

**Comment by sandrinebedard** [comment]
Great! Thanks, I'll test it out again!

**Comment by sandrinebedard** [comment]
hmm, I don't seem to have writing permission for uk-biobank-processed :

```console
(base) sebeda@joplin:~/data_nvme_sebeda/uk-biobank-processed$ ssh git@data.neuro.polymtl.ca info
hello sandrine, this is git@data running gitolite3 3.6.11-2 (Debian) on git 2.27.0

 R   C  datasets/..*
 R      datasets/data-single-subject_DO-NOT-USE
 R      datasets/sct-testing-large
 R      datasets/t1
 R      datasets/t2
 R      datasets/t3
 R      datasets/t4
 R      datasets/uk-biobank
 R      datasets/uk-biobank-processed
 ```

**Comment by kousu** [comment]
>.< sorry! slippy 3am fingers. This inspired me to clean up a bunch of stuff I'd been putting off here and while doing https://github.com/neuropoly/data-management/issues/19#issuecomment-805590660 I erased your permission again.

It should be back now!

**Comment by sandrinebedard** [comment]
it is back! Everything seems to work!
