### ISSUE TITLE
Possible rosenberg git annex issue

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#81]
@charleygros tried to clone **msseg_challenge_2021** on `nvme` on `rosenberg`. He got this message:

```
chgroc@rosenberg:~/data_nvme_chgroc/msseg_challenge_2021$ git annex init
git: 'annex' is not a git command. See 'git --help'.
```

@kousu Could you please help him debug the issue?

**Comment by kousu** [comment]
@charleygros, I believe you're working in conda already? [Just do](https://github.com/neuropoly/data-management/blob/master/git-annex.md#download) `conda install git-annex` in the same env as ivadomed and then you can get on with your work.

Diagnosis: this is a solved problem, except that I need to do https://github.com/neuropoly/computers/issues/81 to make rosenberg uniform with the rest of our infra. But I don't want to disrupt it while it's in use, especially because it has a bunch of custom configs I'm unaware of and because it needs a `do-release-upgrade` and then probably needs the GPU driver readjusted, so it's kind of a big task.

**Comment by charleygros** [comment]
Weeee! THanks @kousu, it fixes my issue!

Just so you know, I had to run the following:
```
conda config --append channels conda-forge
conda install -f conda-forge git-annex
```
